name: CI

on: [push, pull_request, issues, fork, label, milestone, project, project_column]

jobs:
  my-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        prefix:
        - pkg
        - src
    steps:
    - uses: actions-go/modified@master
      id: is-modified
      with:
        pattern: ${{ matrix.prefix }}/**/*.go
    - run: echo "${{ steps.is-modified.outputs.modified }} ${{ steps.is-modified.outputs.modified-files }}"
    - run: echo "${{ steps.is-modified.outputs.modified }} ${{ steps.is-modified.outputs.modified-files }}"
      if: steps.is-modified.outputs.modified == 'true'
    - uses: actions-go/go-action@master
      if: steps.is-modified.outputs.modified == 'true'
      with:
        milliseconds: 1000
 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        env
        cat ${GITHUB_EVENT_PATH}
    - uses: actions/github-script@0.4.0
      with:
        github-token: ${{ github.token }}
        script: |
          console.log(process.env)
          console.log("ok")
        
    - uses: tjamet/go-action-template@master
      with:
        milliseconds: 1000
