name: CI

on: [push, pull_request, issues, fork, label, milestone, project, project_column]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        env
        cat ${GITHUB_EVENT_PATH}
        
