name: CI

on: [push, pull_request, issues, fork, label, milestone, project, project_column]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        env
        cat ${GITHUB_EVENT_PATH}
    - uses: actions/github-script@0.4.0
      with:
        script: |
          console.log(process.env)
          console.log("ok")
        
    - uses: tjamet/go-action-template@master
      with:
        milliseconds: 1000
